"""publications-by-school-and-department

Revision ID: d8e2297c89bb
Revises: a7b78175dd8b
Create Date: 2025-09-16 15:51:56.807963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8e2297c89bb"
down_revision: Union[str, Sequence[str], None] = "4b7bdf4035f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publications_by_department",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("pub_year", sa.Integer(), nullable=True),
        sa.Column("apc", sa.Integer(), nullable=True),
        sa.Column("open_access", sa.String(), nullable=True),
        sa.Column("types", sa.String(), nullable=True),
        sa.Column("federally_funded", sa.Boolean(), nullable=True),
        sa.Column("academic_council_authored", sa.Boolean(), nullable=True),
        sa.Column("faculty_authored", sa.Boolean(), nullable=True),
        sa.Column("primary_school", sa.String(), nullable=True),
        sa.Column("primary_department", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publications_by_school",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("pub_year", sa.Integer(), nullable=True),
        sa.Column("apc", sa.Integer(), nullable=True),
        sa.Column("open_access", sa.String(), nullable=True),
        sa.Column("types", sa.String(), nullable=True),
        sa.Column("federally_funded", sa.Boolean(), nullable=True),
        sa.Column("academic_council_authored", sa.Boolean(), nullable=True),
        sa.Column("faculty_authored", sa.Boolean(), nullable=True),
        sa.Column("primary_school", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publications_by_school")
    op.drop_table("publications_by_department")
    # ### end Alembic commands ###
