#!/bin/bash

# This script is called by our weekly dependency update job in Jenkins

pip3 install --upgrade uv > rialto-airflow.txt &&
    ~/.local/bin/uv lock --upgrade >> rialto-airflow.txt

retVal=$?

git add uv.lock &&
    git commit -m "Update Python dependencies"

if [ $retVal -ne 0 ]; then
    echo "ERROR UPDATING PYTHON (rialto-airflow)"
    cat rialto-airflow.txt
fi
