import datetime

from sqlalchemy import select

from rialto_airflow.database import get_session
from rialto_airflow.schema.rialto import Harvest, RIALTO_DB_NAME


def create_harvest() -> Harvest:
    with get_session(RIALTO_DB_NAME).begin() as session:
        harvest = Harvest()
        session.add(harvest)
        # Sends INSERT now (before commit), so autogenerated fields like id are available.
        session.flush()
        # Returned object is detached (safe to return outside session scope)
        session.expunge(harvest)
        return harvest


def get_harvest_by_id(harvest_id: int) -> Harvest | None:
    with get_session(RIALTO_DB_NAME).begin() as session:
        harvest = session.get(Harvest, harvest_id)
        if harvest is not None:
            session.expunge(harvest)
        return harvest


def get_previous() -> Harvest | None:
    with get_session(RIALTO_DB_NAME).begin() as session:
        harvest = session.execute(
            select(Harvest)
            .where(Harvest.finished_at.is_not(None))
            .order_by(Harvest.id.desc())
            .limit(1)
        ).scalar_one_or_none()
        if harvest is not None:
            session.expunge(harvest)
        return harvest


def complete_harvest(harvest_id: int) -> None:
    with get_session(RIALTO_DB_NAME).begin() as session:
        harvest = session.get(Harvest, harvest_id)
        if harvest is None:
            raise ValueError(f"Harvest {harvest_id} not found")
        harvest.finished_at = datetime.datetime.now(datetime.timezone.utc)
