"""initialize rialto db

Revision ID: 53aa35d55767
Revises:
Create Date: 2026-04-21 14:58:58.611849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53aa35d55767"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sunet", sa.String(), nullable=True),
        sa.Column("cap_profile_id", sa.String(), nullable=True),
        sa.Column("orcid", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("academic_council", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("schools", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("departments", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("primary_school", sa.String(), nullable=True),
        sa.Column("primary_dept", sa.String(), nullable=True),
        sa.Column("primary_division", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cap_profile_id"),
        sa.UniqueConstraint("orcid"),
        sa.UniqueConstraint("sunet"),
    )
    op.create_table(
        "funder",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("grid_id", sa.String(), nullable=True),
        sa.Column("ror_id", sa.String(), nullable=True),
        sa.Column("openalex_id", sa.String(), nullable=True),
        sa.Column("federal", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grid_id"),
        sa.UniqueConstraint("openalex_id"),
        sa.UniqueConstraint("ror_id"),
    )
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("pub_year", sa.Integer(), nullable=True),
        sa.Column("open_access", sa.String(), nullable=True),
        sa.Column("apc", sa.Integer(), nullable=True),
        sa.Column(
            "dim_json",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "openalex_json",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "sulpub_json",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "wos_json",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "pubmed_json",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "crossref_json",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("wos_id", sa.String(), nullable=True),
        sa.Column("pubmed_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("journal_name", sa.String(), nullable=True),
        sa.Column("academic_council_authored", sa.Boolean(), nullable=True),
        sa.Column("faculty_authored", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_index(
        "idx_dim_id",
        "publication",
        [sa.literal_column("(dim_json->>'id')")],
        unique=False,
    )
    op.create_index(
        "idx_openalex_id",
        "publication",
        [sa.literal_column("(openalex_json->>'id')")],
        unique=False,
    )
    op.create_index("idx_pub_pubmed_id", "publication", ["pubmed_id"], unique=False)
    op.create_index("idx_pub_wos_id", "publication", ["wos_id"], unique=False)
    op.create_index(
        "idx_sulpub_id",
        "publication",
        [sa.literal_column("(sulpub_json->>'sulpubid')")],
        unique=False,
    )
    op.create_index(
        "idx_wos_id",
        "publication",
        [sa.literal_column("(wos_json->>'UID')")],
        unique=False,
    )
    op.create_table(
        "pub_author_association",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["author.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["publication.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("publication_id", "author_id"),
    )
    op.create_table(
        "pub_funder_association",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("funder_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["funder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publication.id"],
        ),
        sa.PrimaryKeyConstraint("publication_id", "funder_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pub_funder_association")
    op.drop_table("pub_author_association")
    op.drop_index("idx_wos_id", table_name="publication")
    op.drop_index("idx_sulpub_id", table_name="publication")
    op.drop_index("idx_pub_wos_id", table_name="publication")
    op.drop_index("idx_pub_pubmed_id", table_name="publication")
    op.drop_index("idx_openalex_id", table_name="publication")
    op.drop_index("idx_dim_id", table_name="publication")
    op.drop_table("publication")
    op.drop_table("funder")
    op.drop_table("author")
    # ### end Alembic commands ###
