"""add provenance columns

Revision ID: ad881a79ea4d
Revises: cc4fc6468480
Create Date: 2026-04-27 16:38:10.515894

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad881a79ea4d"
down_revision: str | Sequence[str] | None = "cc4fc6468480"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publication",
        sa.Column(
            "openalex_harvested",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.add_column(
        "publication",
        sa.Column(
            "dim_harvested",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.add_column(
        "publication",
        sa.Column(
            "sulpub_harvested",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.add_column(
        "publication",
        sa.Column(
            "wos_harvested",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.add_column(
        "publication",
        sa.Column(
            "pubmed_harvested",
            sa.DateTime(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publication", "pubmed_harvested")
    op.drop_column("publication", "wos_harvested")
    op.drop_column("publication", "sulpub_harvested")
    op.drop_column("publication", "dim_harvested")
    op.drop_column("publication", "openalex_harvested")
    # ### end Alembic commands ###
